markdown: kramdown

kramdown:
   input: GFM
   hard_wrap: false
   syntax_highlighter: rouge
   syntax_highlighter_opts: { default_lang: javascript }

url: http://breeze-sandbox.github.io

encoding: utf-8
gems:
  - jekyll-redirect-from
  - jekyll-sitemap


